language: node_js
node_js:
  - "9"
  - "8"
  - "6"
  - "4"

sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install leaflet@^1.2.0 togeojson@^0.16.0 --no-save

script:
  - "npm test"
