name: CI

on:
  pull_request:
  push:
    branches:
      - master
  release:
    types:
      - created
  schedule:
    - cron: '0 2 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: 'npm'
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    name: Node ${{ matrix.node }} e2e test
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci
      - run: npm install leaflet@^1.2.0 @mapbox/togeojson@^0.16.0 --no-save

      - name: Cypress run
        uses: cypress-io/github-action@v2

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
            name: cypress-screenshots
            path: cypress/screenshots
        # Test run video was always captured, so this action uses "always()" condition
        - uses: actions/upload-artifact@v2
          if: always()
          with:
            name: cypress-videos
            path: cypress/videos

  publish:
    needs: [lint, test]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}